### ISSUE TITLE
"package invalid"

### ISSUE THREAD

**Issue by DC7IA** [danielgjackson/noisecancel#2]
My phone tells me that the app could not be installed because apparently it is invalid.

Not sure what that means.

I'm running Android 12.

**Comment by DC7IA** [comment]
Tries both v1.0 and v1.1, same result.

I managed to install it from Play Store using Aurora Store, though. If I try to install the APK from GitHub it just fails.

**Comment by Mrsevic** [comment]
Same thing for me. Thanks for the tip regarding Play Store.

**Comment by danielgjackson** [comment]
Thanks for the bug report.

Note: The version on Google play is a bit older (no support for QC 35/QC 45/QC earbuds) -- I should really update that one!

I think the cause was that the APK was not properly signed.

I've released a new version of the APK: https://github.com/danielgjackson/noisecancel/releases/tag/1.2
...hopefully this fixes the issue.

I'll close the bug, but please comment if there's still an issue and I'll reopen.
